# baseURL = "https://horriblyunderqualified.com/"
# languageCode = "en-us"
# title = "Horribly Underqualified"
# theme = "cocoa-eh"
# builddrafts = true
# enableRobotsTXT = true
# canonifyurls = true
# contentdir = "content"
# layoutdir = "layouts"
# publishdir = "public"
# author = "Nicholas Yang"
# disqusshortname = ""
# pluralizelisttitles = false

# [params]
# dateform = "Jan 2, 2006"
# dateformfull = "Mon Jan 2 2006 15:04:05 MST"
# description = "Blog about programming and various other things"
# copyright = "Copyright © 2020 Nicholas Yang"
# logofile = "img/logo.png"
# nofaviconfile = "img/logo.png"
# highlightjs = true
# progressively = true
# align_left = false
# lang = "en"
# github = "nicholaslyang"
# email = "nick@nicholasyang.com"
# linkedin = "nicholaslyang"
# social_banner = "img/banner.png"
# posts_navigation = true
# small_banner_logo = false

languageCode = "en-us"
baseUrl = "https://horriblyunderqualified.com"
title = "Horribly Underqualified"
theme = "anubis"
paginate = 10
enableRobotsTXT = true

[menu]
  [main]
    identifier = "archive"
    name = "Archive"
    title = "Archive"
    url = "/posts/"
    weight = "0"

[params]
author = "Nicholas Yang"
description = "A blog on programming and other things"
copyright = "Copyright © 2020 Nicholas Yang"
highlightjs = true